name: Security checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  codeql:
    name: CodeQL analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript,typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v2

  dependency-audit:
    name: Dependency audit (Yarn)
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Ensure Yarn (Corepack)
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run yarn audit
        # Fail the job if vulnerabilities >= moderate are found
        run: yarn audit --level moderate
